 

  /*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function BlenderStone(props) {
  const { nodes, materials } = useGLTF('/blender-stone.glb')
  return (
    <group {...props} dispose={null} scale={0.5}>
      <group position={[-2.534, 26.092, -9.173]} rotation={[-Math.PI / 2, 0, 0]} scale={10.587}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.cream_cream_Material_0.geometry}
              material={materials.cream_Material}
              position={[-0.83, -1.626, -0.158]}
              rotation={[0, 0, -0.454]}
              scale={1.75}
            />
          </group>
        </group>
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder.geometry}
        material={nodes.Cylinder.material}
        position={[2.231, -25.845, 9.904]}
        scale={53.478}
      />
    </group>
  )
}

useGLTF.preload('/blender-stone.glb')