/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Seashell(props) {
  const { nodes, materials } = useGLTF('/Seashell.glb')
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh_0.geometry}
        material={materials.Material_0}
        position={[0.135, -0.579, 0.603]}
        rotation={[-1.504, -0.237, 2.576]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh_0001.geometry}
        material={materials['Material_0.001']}
        position={[0.093, 0.164, 0.156]}
        rotation={[0.512, -0.035, -0.149]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Sphere.geometry}
        material={materials['Mother of pearl']}
        position={[0.151, -0.6, 0.335]}
        scale={0.132}
      />
    </group>
  )
}

useGLTF.preload('/Seashell.glb')